import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Uses from '../components/Uses'
import Testimonials from '../components/Testimonials'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next.js Landing Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Hero />
      <Uses />
      <h1 className='text-center pt-36 font-bold text-5xl'>Rock Users</h1>
      <div className='flex justify-evenly p-36'>
        <Testimonials />
      </div>
    </div>
  )
}
